### ISSUE TITLE
Gear Up and Go acting funny with Giddy Up Ride and Roll

### ISSUE THREAD

**Issue by rushuna86** [alextd/Rimworld-GearUpAndGo#6]
I've noticed that if a colonist is currently mounted, and you use the Gear Up and Go button and place the location you want them far away from the storage. Instead of going to the gear up, mounted pawn will ride mount to location then ride mount back n forth between clothing position and set meet up location equipping one piece of equipment at a time :D

**Comment by alextd** [comment]
Ah, gee, that makes no sense and I'm not about to try to figure out why this other silly mod breaks it,

I suggest not doing that again

**Comment by arvalaan** [comment]
This makes these mod unusable together, too bad you're not wanting to look into it, would've been cool! Thanks for the effort you've put in the mod regardless :-)
